### ISSUE TITLE
Could not prefetch network_config provider 'default'

### ISSUE THREAD

**Issue by joshuabaird** [crayfishx/network_config#16]
I'm using this module to manage a bunch of hosts that have ```/etc/sysconfig/network-scripts/ifcfg-eth0``` files that look like this:

```
DEVICE=eth0
BOOTPROTO=static
HWADDR=00:21:9b:a3:02:44
ONBOOT=yes
HOTPLUG=yes
TYPE=Ethernet
IPADDR=172.26.101.131
NETMASK=255.255.252.0
GATEWAY=172.26.100.1
PEERDNS=no
NM_CONTROLLED=no
```

On some of the hosts, Puppet is throwing this error during the initial run with this module:

```
Error: Could not prefetch network_interface provider 'default': No name found in /etc/sysconfig/network-scripts/ifcfg-eth0:1
Notice: /Stage[main]/Base::Network/Network_interface[eth0]/ensure: created
Error: Could not prefetch ip_allocation provider 'default': No name found in /etc/sysconfig/network-scripts/ifcfg-eth0:1
```

This is probably because I don't have ```NAME``` defined in the network config file.  Most of time, this error fixes it's self because the module adds the ```NAME``` line and all is fine the next run.

However, if the host has other ```/etc/sysconfig/network-scripts/ifcfg-eth*``` files, the module contentiously errors out on them (see the ``ifcfg-eth0:1``` definition below):

```
Error: Could not prefetch network_interface provider 'default': No name found in /etc/sysconfig/network-scripts/ifcfg-eth0:1
Notice: /Stage[main]/Base::Network/Network_interface[eth0]/ensure: created
Error: Could not prefetch ip_allocation provider 'default': No name found in /etc/sysconfig/network-scripts/ifcfg-eth0:1
```

I'm not managing ```ifcfg-eth0:1``` with this module (and don't want to).  It also keeps adding a new ```IPADDR``` definition to ```/etc/sysconfig/network-scripts/ifcfg-eth0``` during each run like so:

```
DEVICE=eth0
BOOTPROTO=static
HWADDR=00:21:9b:a3:02:44
ONBOOT=yes
HOTPLUG=yes
TYPE=Ethernet
IPADDR=172.26.101.131
NETMASK=255.255.252.0
GATEWAY=172.26.100.1
PEERDNS=no
NM_CONTROLLED=no
NAME=eth0
IPADDR1=172.26.101.131
NETMASK1=255.255.252.0
GATEWAY1=172.26.100.1
IPADDR2=172.26.101.131
NETMASK2=255.255.252.0
GATEWAY2=172.26.100.1
IPADDR3=172.26.101.131
NETMASK3=255.255.252.0
GATEWAY3=172.26.100.1
IPADDR4=172.26.101.131
NETMASK4=255.255.252.0
GATEWAY4=172.26.100.1
IPADDR5=172.26.101.131
NETMASK5=255.255.252.0
...
```

The only way to resolve this is to manually define ```NAME``` in the other ifcfg-eth* files (even ones that we aren't managing with this module), or to delete the file.  I also have to go back into the ```ifcfg-eth0``` file and delete all the duplicate ```IPADDR``` lines that it created.

Any idea here?

**Comment by crayfishx** [comment]
We definitely need better handing of this... 

One question though - why do you have an `ifcfg-eth0:1` on a NetworkManager based system? you've said you don't want to manage this file so why is it there?

**Comment by joshuabaird** [comment]
I'm planning on using this module to manage hosts without NetworkManager as well, which is how I noticed this problem.  In that case, I'm doing something like this:

```
      if ($networkmanager) {

        # Use NetworkManager to configure static network interface
        network_interface { 'eth0':
          ensure        => 'present',
          bootproto     => 'static',
          device        => 'eth0',
          ipv6init      => 'no',
          onboot        => 'yes',
          dns1          => $dns1,
          dns2          => $dns2,
          domain        => $domain,
          peerdns       => 'yes',
          nm_controlled => 'yes',
        }
        ip_allocation { $myip:
          ensure    => 'present',
          gateway   => $default_gateway,
          interface => 'eth0',
          netmask   => $mynetmask,
        }
      } else {

        # Do *not* use NetworkManager to configure static interface (default)
        service { 'NetworkManager':
            ensure => 'stopped',
        }
        network_interface { 'eth0':
          ensure        => 'present',
          bootproto     => 'static',
          device        => 'eth0',
          onboot        => 'yes',
          peerdns       => 'no',
          nm_controlled => 'no',
        }
        ip_allocation { $myip:
          ensure    => 'present',
          gateway   => $default_gateway,
          interface => 'eth0',
          netmask   => $mynetmask,
        }
      }
```

So, I have files like ```ifcfg-eth0:1``` on lots of older systems that aren't using NetworkManager.
