### ISSUE TITLE
GATEWAY[X] definitions are created even when NetworkManager is disabled

### ISSUE THREAD

**Issue by joshuabaird** [crayfishx/network_config#19]
On a host where NetworkManager is disabled (by setting ```nm_controlled``` to ```no```), the module still tries to append a number to the ``IPADDR`` line in ``/etc/sysconfig/network-scripts/ifcfg-ethX`` like so:

```
# Generated by dracut initrd
NAME="eth0"
HWADDR=00:50:56:B8:30:7B
ONBOOT=yes
NETBOOT=yes
UUID="ef24f0a2-b5c7-4a93-970d-6ff5a273a49c"
IPV6INIT=yes
BOOTPROTO=static
TYPE=Ethernet
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
PEERDNS=no
PEERROUTES=yes
IPV6_PEERDNS=yes
IPV6_PEERROUTES=yes
DEVICE=eth0
NM_CONTROLLED=no
IPADDR0=172.21.100.17
NETMASK0=255.255.252.0
GATEWAY0=172.21.100.1
```

This is the result of this code:

```
network_interface { 'eth0':
  ensure        => 'present',
  bootproto     => 'static',
  device        => 'eth0',
  onboot        => 'yes',
  peerdns       => 'no',
  nm_controlled => 'no',
}

ip_allocation { $myip:
  ensure    => 'present',
  gateway   => $::default_gateway,
  interface => 'eth0',
  netmask   => $mynetmask,
}
```
This effectively breaks networking for non-NetworkManager systems. It appears to break the default route leaving only hosts on the system's subnet accessible.  The only way to fix it, in my experience thus far, is to remove the ```0``` from the ```IPADDR``` line.

So - I'm still testing, but I wonder if we should prevent the module from numbering IPADDR lines when ```nm_controlled``` is set to ```no```?  Haven't checked to see how easy (or hard) this would be yet.

**Comment by joshuabaird** [comment]
Ok - so it looks like IPADDRx may actually be supported even on non-NM systems.  Still testing here.

**Comment by joshuabaird** [comment]
The problem is that the module is appending a number to the ```GATEWAY``` param:

```
IPADDR0=blah
GATEWAY0=blah
```

Multiple ``GATEWAY`` definitions are not supported, thus breaking the default route for the host.

**Comment by joshuabaird** [comment]
The way to manually fix this is to remove the 'X' numbers from ``IPADDR``, ``NETMASK`` and ``GATEWAY`` lines on non-NM managed systems.  The problem is that this module automatically adds the 'X' numbers if a definition does not already exist.

Is there a way we can keep the module from appending the 'X' numbers on non-NM managed systems?

**Comment by joshuabaird** [comment]
@crayfishx any ideas here?

**Comment by crayfishx** [comment]
@joshuabaird This module is mainly designed for NM managed systems - I haven't used it on a non NM (eg: RHEL6) system.  We could easily make it drop the iterator but then how do we handle multiple ip_allocation declarations on the same interface?

**Comment by joshuabaird** [comment]
So here is the plan (per discussion with @crayfishx):

We'll introduce a new `GATEWAY` parameter on `network_interface` which will add `GATEWAY=blah` to the interface configuration.  This is sufficient for non-NM managed systems which will break if you specify `GATEWAYx` in the interface configuration files.  For non-NM managed systems, a user can simply omit `GATEWAY` on `ip_allocation`.  

While this may be a bit confusing for users, it's a way to fix this issue without breaking functionality for existing users of this module.

PR coming soon.

**Comment by joshuabaird** [comment]
#20 submitted.
